language: node_js
cache:
  yarn: true
  directories:
    - node_modules
branches:
  except:
  - v2
  - 2.1
sudo: false
env:
- CXX=g++-4.8
addons:
  ssh_known_hosts:
    - cheddar.fuelrats.com
  postgresql: '9.5'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- 8.8.1
services:
- postgresql
before_script:
- psql -c 'create database fuelratstest;' -U postgres
- psql -c 'create extension citext;' -U postgres fuelratstest
- psql -c 'CREATE USER fuelrats;' -U postgres
- psql -c "ALTER USER fuelrats PASSWORD 'fuelrats';" -U postgres
notifications:
  webhooks:
    urls:
      - http://orthanc.localecho.net/cgi-bin/webhook.py
    on_success: always
    on_failure: always
before_deploy:
  - openssl aes-256-cbc -K $encrypted_1c3e6d732708_key -iv $encrypted_1c3e6d732708_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/dev.api.fuelrats.com/
  on:
    branch: develop

- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/api.fuelrats.com/
  on:
    branch: master
